KIP13 - Transient Storage Handling
kaspanet/kips pull request #22
Opened 2024-12-29 18:03 UTC by coderofstuff

## Summary

We propose tracking the transient storage consumption of transactions as a mass and bounding such consumption to a reasonable size for node operators.

2025-01-06 15:58 UTC, michaelsutton submitted a review, later dismissed

2025-01-07 08:04 UTC, someone235 requested changes

2025-01-07 08:04 UTC, someone235 commented on kip-0013.md
> +```
This is more of a stylistic comment, so it's up to you to decide whether you like it or not.

I think it's better to first outline our general motivation, that is, to be able limit block size independently, then describe the proposed consensus changes, and in a later section justify the choice of assignments to the constants (basically why we chose 4). The last section should explain that we want to limit to ~200GB transient storage while preserving the current TPB for 1:2 and 2:2 transactions, and how choosing 4 serves that purpose.

2025-01-07 08:05 UTC, someone235 commented on kip-0009.md
> +**Transaction mass field** A new explicit `mass` field should be added to the `Transaction` structure. This field is used as a *commitment* to the storage mass consumed by the transaction, until it c
I checked with him in another channel and seems like it won't impose a problem

2025-01-12 03:22 UTC, coderofstuff commented on kip-0013.md
> +```
I've kept the current format, but I added the motivation as the first paragraph under the `#Motivation` section

2025-01-12 13:06 UTC, someone235 requested changes

2025-01-12 13:06 UTC, someone235 commented on kip-0013.md
> +We propose tracking the transient storage consumption of transactions as a `mass` and bounding such consumption to a reasonable size for node operators. In the Kaspa jargon, the word `mass`` is used
Typo: you wrote `mass`` with double backtick

2025-01-12 13:06 UTC, someone235 commented on kip-0013.md
> +Since KIP9, transactions now consume two types of masses, compute mass and storage mass. These masses are used to limit some consumption of resource per block (compute and persitent storage, respecti
"However, either of these". Did you mean "neither"?

2025-01-12 13:06 UTC, someone235 commented on kip-0013.md
> +Since KIP9, transactions now consume two types of masses, compute mass and storage mass. These masses are used to limit some consumption of resource per block (compute and persitent storage, respecti
"We need to have a way to limit block byte sizes directly to have finer control over the worst-case storage used by a node." Maybe also mention bandwidth?

2025-01-12 18:16 UTC, someone235 approved these changes

2025-01-12 18:17 UTC, merged